### ISSUE TITLE
rollbar_environment is always 'production' unless i explicitly set it to a different env

### ISSUE THREAD

**Issue by deXterbed** [code-lever/mina-rollbar#2]
Here's my deploy.rb:

``` ruby
on_server = ENV['on'] || 'staging'
branch = ENV['branch'] || 'master'

if on_server == 'staging'
  set :domain, '####'
  set :deploy_to, "####"
  set :branch, '####'
  env = 'staging'
elsif on_server == 'demo'
  set :domain, '####'
  set :deploy_to, "####"
  set :branch, 'demo'
  env = 'staging'
elsif on_server == 'production'
  set :domain, '####'
  set :deploy_to, "####"
  set :branch, 'production'
  env = 'production'
elsif on_server == 'testing'
  set :domain, '####'
  set :deploy_to, "####"
  set :branch, '####'
  env = 'staging'
end

set :repository, 'git@github.com:####.git'
set :user, 'ubuntu'
set :rails_env, env
set :identity_file, '####'
set :rollbar_access_token, '####'
# set :rollbar_environment, rails_env
```

Now, when i do  `on=testing mina deploy`, my rollbar_environment is always 'production'. I think setting the rollbar_environment is completely unnecessary, it should infer the env from rails_env variable automatically.

**Comment by deXterbed** [comment]
here's my output from `on=testing mina deploy -S`

``` bash
&& (

  echo "-----> Notifying Rollbar of deployment"

) && (
curl -s -o /dev/null https://api.rollbar.com/api/1/deploy/ -F access_token=##### -F environment=production -F revision=#### -F local_username=####
)
```

**Comment by nickveys** [comment]
`rollbar_environment` does (or should) get the environment from `rails_env` if it is available.  It was added to support non-rails deployment environments here: https://github.com/code-lever/mina-rollbar/commit/5b6cc0529cca62477bb99399cec1a578d5843c6d

I can't tell if you're using rails or not there, but does setting the `rollbar_environment` not work for you?

**Comment by deXterbed** [comment]
@nickveys thanks for the response nick, setting `rollbar_environment` works for me, but my point is do i really need to set it? shouldn't it be picked up from the line `set :rails_env, env` right above it?

**Comment by deXterbed** [comment]
@nickveys i am using rails 4.1.10, mina 0.3.7

**Comment by nickveys** [comment]
Absolutely, I don't set `rollbar_environment` in any of my projects, since I'm using Rails, and have `mina/rails` required in my deploy script, it sets `rails_env` for me.  And this gem takes that value by default.

I think I understand your issue now...  I'll push a new version shortly.

**Comment by nickveys** [comment]
New version pushed out to RubyGems.org, it was pulling the `rails_env` value before you had a chance to change it in your scripts so it was always `production`.

**Comment by deXterbed** [comment]
@nickveys thanks a lot! :))
