### ISSUE TITLE
Update plan

### ISSUE THREAD

**Issue by jakoss** [code-lever/mina-rollbar#6]
Hi,

Do you plan to update this library to work with mina `~> 1.2.3`?

I looked briefly on your code and i don't think it will be problematic (possibly just mina version bump in gemspec)

**Comment by nickveys** [comment]
The gemspec is already set to `~> 1.0`, so it shouldn't prevent you from using `bundle update`to any 1.x version.  If there are problems beyond that, please feel free to open another issue!

**Comment by Nekromancer** [comment]
![image](https://user-images.githubusercontent.com/3933348/43184409-cb10ea18-8fe8-11e8-9c93-1f7675e63299.png)

**Comment by jakoss** [comment]
Thanks. I haven't notice that there are newer versions of mina-rollbar since they are not in releases tab :)
